export {Skills} from './skills'
export {Portfolio} from './portfolio'
export {NavBar} from './nav'
export {Header} from './header'
export {Footer} from './footer'
export {Contacts} from './contacts'
export {About} from './about'
export {ButtonOnTop} from './buttonOnTop'